gitea:
   container_name: gitea
   image: gitea/gitea:1.23
   envi









    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 1
        #delay: 30s
        order: start-first
      #restart_policy:
        #condition: any
        #delay: 20s
        #window: 60s
      placement:
         constraints: [node.hostname == srv1]
         
