---
version: '3.8'

services:
  postgres:
    container_name: postgres-1
   # image: postgres:latest
    image: postgres:15-bookworm
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /data/dir2:/var/lib/postgressql/data
    environment:
      POSTGRES_PASSWORD: password123
      POSTGRES_USER: postgres
      POSTGRES_DB: my_db
